version: 2.1

jobs:
  build:
    docker:
      - image: level12/python-test-multi

    steps:
      - checkout

      - run:
          name: install tox
          command: pip3.12 install tox

      - run:
          name: install flake8-level12
          command: pip3.12 install git+https://github.com/level12/flake8-level12.git

      - run:
          name: tox
          command: tox

      - store_test_results:
          path: .circleci/test-reports/

      - run:
          name: push code coverage
          command: bash <(curl -s https://codecov.io/bash) -X coveragepy -t "5b9c35e6-a963-496d-9f83-d65ba6444898"
